language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: false

install: composer update --prefer-dist

script:
    - find src tests -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
    - vendor/bin/php-cs-fixer fix --dry-run --diff
    # - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi

after_script:
    - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
